name = "crawl4ai-mcp-server"
main = "src/index.ts"
compatibility_date = "2023-05-03"

# Specify worker environment
workers_dev = true
usage_model = "bundled"
compatibility_flags = ["nodejs_compat"]

# KV namespace for storing crawl data
kv_namespaces = [
  { binding = "CRAWL_DATA", id = "", preview_id = "" }
]

# Environment variables
[vars]
API_VERSION = "v1"
MAX_CRAWL_DEPTH = "3"
MAX_CRAWL_PAGES = "100"

# Development environment
[env.development]
name = "crawl4ai-mcp-server-dev"
vars = { MAX_CRAWL_DEPTH = "2", MAX_CRAWL_PAGES = "10" }

# Production environment
[env.production]
name = "crawl4ai-mcp-server"
routes = [
  { pattern = "crawl4ai-mcp.yourdomain.com", custom_domain = true }
]

# Build settings
[build]
command = "npm run build"